### PR TITLE
Close #93, automatically deploy documentation on push to main

### LINKED ISSUE #93: Discuss deploying with push to main
Docusaurus 2 docs: https://v2.docusaurus.io/docs/deployment/#triggering-deployment-with-github-actions

### PR DESCRIPTION
**Pull request by plocket**
## Still to do

It works as it is now, but we should decide if we want to put someone's username and email in deploy.yml. Feel free to edit that in if you want it.

## More info

Also runs a test deploy when a PR is made to main. Both workflows are based on docusaurus code that's linked in #93.

I tested it on a fork and all seemed well. That said, I'm not sure how well the actions communicate. For example, they didn't error when a non-existent directory was referenced, just created a 404 with no clues.

In addition to the docusaurus code, I've added the ability to manually trigger both the test and the deployment of main, for whatever good that does.

Note: This might only start working once it's been merged with main.

Closes #93

### CODE REVIEW

**Comment by nonprofittechy** [comment]
I wonder if difference in build/deploy success is just a configuration option? I know build works with broken links but deploy does not. But you can turn off the stricter rule. If that would help tests be more accurate that could be worthwhile.

**Comment by plocket** [comment]
> I wonder if difference in build/deploy success is just a configuration option?

I looked through https://docusaurus.io/docs/api/docusaurus-config. Regarding broken links, by default they should cause an error on build from what I read. Maybe we have a different configuration. Regarding a wrong directory, I didn't find anything specific to the problem I ran into.

I'm not sure what other problems we want to try to head off at the pass. Potentially [broken markdown links](https://docusaurus.io/docs/api/docusaurus-config#onbrokenmarkdownlinks) or [duplicate routes](https://docusaurus.io/docs/api/docusaurus-config#onduplicateroutes).

Is this a blocking consideration for this issue, or should it be made into its own issue?

**Comment by plocket** [comment]
To clarify, I'm not worried about a problem with the wrong directory again - I worked out that problem and I'm not sure why it would come up again. I was just using it as example of a situation where I thought I would have seen a useful error, but didn't. It makes me wonder how they're handling other potential problems and I think we should just be aware of it moving forward.

**Comment by nonprofittechy** [comment]
Happy to give it a try and tweak later. With extra caution around changes that are likely to break things, such as adding new pages. This looks good to me, just wasn't ready to review late last night.

**Review by nonprofittechy — APPROVED** [review]

**Pull request merged**
