### PR TITLE
Init docusaurus v2 with node

### PR DESCRIPTION
**Pull request by plocket**
No customizations, just the bare install. [This uses nodejs. I'm more familiar with node. If we want to use yarn, there are further questions to discuss.]

### CODE REVIEW

**Comment by nonprofittechy** [comment]
I'm not going to be able to meaningfully review this. I think proof will be in getting a working website up.

**Comment by plocket** [comment]
Do you mean we should merge this or that we shouldn't merge this till we have a ghpages working with it? The website loads for me locally. I was hoping someone else could check that.

**Comment by plocket** [comment]
☝️ @nonprofittechy

**Comment by nonprofittechy** [comment]
I don't have capacity to review and I don't think it will be very useful to add my review.

**Comment by plocket** [comment]
Note: Flying solo is the plan for now 👍

**Pull request merged**
