### PR TITLE
Close #66, add initial draft of Generic Motion DOCX as synonym to Generic Motion PDF

### LINKED ISSUE #66: Add sample DOCX
Make it match https://github.com/SuffolkLITLab/docassemble-GenericMotionFamilyLaw/blob/master/docassemble/GenericMotionFamilyLaw/data/templates/Generic_Motion_Family_Law_re-labeled.pdf

Here's an example DOCX from the meeting: https://github.com/SuffolkLITLab/docassemble-MotionToSingleJusticeAppeals/blob/main/docassemble/MotionToSingleJusticeAppeals/data/templates/231_118_Suffolk_Lab_template_appeals.docx

### PR DESCRIPTION
**Pull request by plocket**
Closes #66. Test:
- [ ] It runs

### CODE REVIEW

**Comment by BryceStevenWilley** [comment]
This doesn't actually link anywhere to the docx, and since docasaurs adds some hash on the asset url (like `http://localhost:3000/docassemble-AssemblyLine-documentation/assets/files/generic_motion_family_law-4e8ec303c6cb2da97f64ce2c95c6bda7.pdf`), we won't be able to link to it externally either?

**Comment by plocket** [comment]
> This doesn't actually link anywhere to the docx, and since docasaurs adds some hash on the asset url (like `http://localhost:3000/docassemble-AssemblyLine-documentation/assets/files/generic_motion_family_law-4e8ec303c6cb2da97f64ce2c95c6bda7.pdf`), we won't be able to link to it externally either?

It just adds the file to the repo. Maybe we won't link to the internal file in the end, but it should still probably live in this repo. I think. Would appreciate other thoughts/ideas.

**Comment by plocket** [comment]
We can make it downloadable this way: ```<a href="./assets/generic_motion_family_law.docx" download target="blank_">Download DOCX file</a>```

**Comment by BryceStevenWilley** [comment]
I figured it could be linked up at the top of a page like the PDF version is in https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/blob/main/docs/pdfs.md. I guess not on that page (which is PDF specific), but maybe https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/blob/main/docs/weaver_overview.md?

**Comment by plocket** [comment]
Yeah, that might be good. This was just to add the doc, though.

**Comment by plocket** [comment]
Or the normal way of linking which I thought didn't work but seems fine now : shrug :

**Pull request merged**
