### PR TITLE
Close #127 add pydoc for AssemblyLine

### LINKED ISSUE #127: Look into setting up Pydoc => Docusaurus v2 workflow
Improve docstrings to match

### PR DESCRIPTION
**Pull request by plocket**
Close #127, MVP for adding pydoc documentation.

### CODE REVIEW

**Comment by plocket** [comment]
I think we actually need to merge into gh-pages for this to take effect, but I'm not sure what our procedure is on that.

**Comment by BryceStevenWilley** [comment]
> I think we actually need to merge into gh-pages for this to take effect, but I'm not sure what our procedure is on that.

Don't think there's a procedure: we just run `GIT_USER=<Your GitHub username> USE_SSH=TRUE npm run deploy`, which runs [docusaurus deploy](https://docusaurus.io/docs/deployment#deploying-to-github-pages), which already modifies gh-pages by default.

**Comment by BryceStevenWilley** [comment]
Added a small fix so now it'll actually show the documentation for all of the modules, not just `al_general`.

**Review by BryceStevenWilley — APPROVED** [review]
LGTM for now. Before trying to use Sphinx or anything, I think the next step is still to hook up github actions, but having some sort of documentation available is a great start.

**Pull request merged**
