### PR TITLE
Close #99, remove landing page, go straight to docs

### LINKED ISSUE #99: Discuss: Route straight to docs and remove landing page
Alternatively, put intro content on landing page instead? The landing page isn't doing much for us right now.

### PR DESCRIPTION
**Pull request by plocket**
Close #99. This is not content tweaks, more of a structural change. Would love a second eye on it, but happy to just merge if it's more convenient.

### CODE REVIEW

**Review by BryceStevenWilley — CHANGES_REQUESTED** [review]
Looks consistent internally, but we do need to add a redirect from http://localhost:3000/docassemble-AssemblyLine-documentation/docs/ (the original "About" page) to http://localhost:3000/docassemble-AssemblyLine-documentation/ (the new "About" page), as the original page 404's, and the side bar isn't there :/

https://v2.docusaurus.io/docs/docusaurus-core#redirect seems relevant, but I don't know enough about docusaurus to know where to add it.

**Comment by plocket** [comment]
Hmm, maybe we can just dynamically redirect to anywhere just processing the current address...

**Comment by plocket** [comment]
Not sure we have access to anything that deep. I'll dig some more, but if I don't find something I'll change direction and try keeping the home page and just redirecting from there.

**Comment by BryceStevenWilley** [comment]
I was going to suggest that, I didn't even realize that all of the existing pages would be 404'd by this as well. One single redirect from the front page to the about page would be good.

**Pull request closed without merging**
